#!/usr/bin/env sh
cd $PWD
case "$1" in
test) docker-compose exec php sh -c "cd /var/www/webapp && /var/www/webapp/vendor/bin/behat";;
shape) docker-compose exec php sh -c "composer install -d /var/www/webapp";;
#) docker-compose ps;;
build) docker-compose build;;
stop) docker stop $(docker ps -q);;
rm) docker-compose down
    docker-sync-stack clean;;
operate) docker-sync-stack start;;
ssh) docker-compose exec "$2" sh;;
services) docker service ps;;
-h) echo "utility usage: now [-key]
    -h: help
    test: runs behat test inside container
    rm: clean docker stack
    build: builds docker container
    operate: run containers and docker-sync
    ssh [service]: ssh into docker service
    ";;
*) now -h
esac